### TEST GET / website
GET http://localhost:3000
### TEST GET /dashboard website
GET http://localhost:3000/dashboard
### TEST GET / DATA ENDPOINT
GET http://localhost:3000/api/data
### TEST POST / DATA ENDPOINT FOR ADDING A NEW USER
POST http://localhost:3000/api/data
Content-Type: application/json

[
    {
    "name": "Alan Mendez",
    "email": "alanmendez@gmail.com",
    "age": 19,
    "city": "Gualajara, Jal, Mexico",
    "ocupation": "Software Engineer",
    "message": "Hello from the server backend"
    },
    {
    "name": "Camila Vega",
    "email": "vegaCamila@gmail.com",
    "age": 20,
    "city": "Los Angeles, CA, USA",
    "ocupation": "Doctor of Veterinary Medicine",
    "message": "Hello from the server backend"
    }
]

### TEST DELETE / DATA ENDPOINT FOR DELETING THE LAST USER
DELETE http://localhost:3000/api/data